Update example

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,6 +1,10 @@
 name: Prueba
 
 on: 
+  push:
+    paths:
+      - 'action.yml'
+
   workflow_dispatch:
 
 jobs:
@@ -9,15 +13,15 @@ jobs:
     name: A job to run test
     steps:
     - name: Clone repository manually
-      run: git clone https://github.com/MasterCloudApps/Template-CI-CD .
+      run: git clone https://github.com/MasterCloudApps/4.2.Integracion-y-entrega-continua-ejem-1 .
     - name: Checkout action
-      uses: actions/checkout@v2
+      uses: actions/checkout@v3
       with:
         path: ./action
     - name: Set up JDK 17
-      uses: actions/setup-java@v2
+      uses: actions/setup-java@v3
       with:
-        distribution: 'adopt'
+        distribution: 'temurin'
         java-version: '17'
     - name: Run Maven Action
       id: maven-gha
@@ -27,4 +31,4 @@ jobs:
         exclude: 'selenium'
     - name: Get project version
       run: |
-        [[ ${{ steps.maven-gha.outputs.project-version }} == "0.1.0" ]] && echo "Works" || ( echo "Fail" && exit 1 )
+        [[ ${{ steps.maven-gha.outputs.project-version }} == "0.0.1-SNAPSHOT" ]] && echo "Works" || ( echo "Fail" && exit 1 )
